#### 说明：
#### 1、numpy.random中的函数shuffle与permutation都是对原来的数组进行重新洗牌（即随机打乱原来的元素顺序），区别在于shuffle直接在原来的数组上进行操作，改变原来数组的顺序，无返回值；而permutation不直接在原来的数组上进行操作，而是返回一个新的打乱顺序的数组，并不改变原来的数组
#### 2、list 和 tuple 无法通过 由位置索引组成的列表（或元组） 一次获取多个不同位置上的子列表或子元组【可以通过切片获取连续位置上的多个元素】，但是数组可以【多个元素的位置索引必须是列表形式，其他形式无效】。ex:

##### ①list

In [96]:
import numpy as np
test_list = list(range(1,21))
print(test_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [97]:
print('test_list[1]:',test_list[1])                # 取列表中的单个元素可以

test_list[1]: 2


In [98]:
print('test_list[1,2]:',test_list[1,2])            # 一次取多个非连续位置上的元素不可以

TypeError: list indices must be integers or slices, not tuple

In [99]:
print('test_list[[1,2]]',test_list[[1,2]])

TypeError: list indices must be integers or slices, not list

##### ②tuple

In [100]:
test_tuple = tuple(test_list)
test_tuple

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [101]:
print('test_tuple[1]:',test_tuple[1])                # 取元组中的单个元素可以

test_tuple[1]: 2


In [102]:
print('test_tuple[1,2]:',test_tuple[1,2])            # 一次取多个非连续位置上的元素不可以

TypeError: list indices must be integers or slices, not tuple

In [103]:
print('test_tuple[[1,2]]',test_tuple[[1,2]])

TypeError: tuple indices must be integers or slices, not list

##### ③数组

In [104]:
test_array = np.array(test_list)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [105]:
print('test_array[1]:',test_array[1])             # 取数组中的单个元素是可以的

test_array[1]: 2


In [107]:
print('test_array[[1,1]]:',test_array[[1,1]])    # 多个位置索引需要时列表形式

test_array[[1,1]]: [2 2]


In [109]:
print('test_array[(1,1)]:',test_array[(1,1)])    # 多个位置索引组成元组形式也不可以

IndexError: too many indices for array

#### 3、在用训练集训练模型的时候，每遍历完一遍所有的数据，需要洗牌一次，此时可以两种方法进行洗牌：
#### 1）、只打乱数据的位置索引，然后根据新的位置索引重排数据——使用permutation函数
#### 2）、直接对整个训练集进行洗牌——使用shuffle函数

##### 查看shuffle函数和permutation函数的详细情况

In [110]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    Parameters
    ----------
    x : array_like
        The array or list to be shuffled.
    
    Returns
    -------
    None
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8]
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.shuffle(arr)
    >>> arr
    array([[3, 4, 5],
           [6, 7, 8],
           [0, 1, 2]])



In [111]:
help(np.random.permutation)

Help on built-in function permutation:

permutation(...) method of mtrand.RandomState instance
    permutation(x)
    
    Randomly permute a sequence, or return a permuted range.
    
    If `x` is a multi-dimensional array, it is only shuffled along its
    first index.
    
    Parameters
    ----------
    x : int or array_like
        If `x` is an integer, randomly permute ``np.arange(x)``.
        If `x` is an array, make a copy and shuffle the elements
        randomly.
    
    Returns
    -------
    out : ndarray
        Permuted sequence or array range.
    
    Examples
    --------
    >>> np.random.permutation(10)
    array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6])
    
    >>> np.random.permutation([1, 4, 9, 12, 15])
    array([15,  1,  9,  4, 12])
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.permutation(arr)
    array([[6, 7, 8],
           [0, 1, 2],
           [3, 4, 5]])

